// Sprite generator for pacman.s: 16x16 1bpp images, pre-shifted to the
// 4 even bit phases (x is always even), 3 bytes per row, 48 bytes per phase.
// Bit 0 is the leftmost pixel (framebuffer convention).
// Splices the .BYTE block into programs/pacman.s between the marker lines.
import { readFileSync, writeFileSync } from 'node:fs';

const B = '................';
const pad = (r) => (r + B).slice(0, 16);

// ---- Pac-Man, mouth facing right; other directions are derived ----
const PAC_CLOSED = [
  B,
  '.....######.....',
  '...##########...',
  '..############..',
  '..############..',
  '.##############.',
  '.##############.',
  '.##############.',
  '.##############.',
  '.##############.',
  '.##############.',
  '..############..',
  '..############..',
  '...##########...',
  '.....######.....',
  B,
];
const PAC_HALF_R = PAC_CLOSED.map((r, y) =>
  ({ 6: '.#########......', 7: '.#######........', 8: '.#######........', 9: '.#########......' }[y] ?? r),
);
const PAC_WIDE_R = PAC_CLOSED.map((r, y) =>
  ({
    3: '..##########....',
    4: '..#########.....',
    5: '.#########......',
    6: '.########.......',
    7: '.######.........',
    8: '.######.........',
    9: '.########.......',
    10: '.#########......',
    11: '..#########.....',
    12: '..##########....',
  }[y] ?? r),
);

// ---- ghost: body with eye holes; A/B differ in the skirt (walk wobble) ----
const ghost = (skirt13, skirt14) => [
  B,
  '.....######.....',
  '...##########...',
  '..############..',
  '..############..',
  '.###..####..###.',
  '.###..####..###.',
  '.###..####..###.',
  '.##############.',
  '.##############.',
  '.##############.',
  '.##############.',
  '.##############.',
  skirt13,
  skirt14,
  B,
];
const GBODA = ghost('.##############.', '.##..##..##..##.');
const GBODB = ghost('.##############.', '..##..####..##..');

// ---- frightened: hollow body, dotted eyes, zigzag mouth ----
const fright = (feet) => [
  B,
  '.....######.....',
  '...##......##...',
  '..#..........#..',
  '..#..........#..',
  '.#............#.',
  '.#..##....##..#.',
  '.#..##....##..#.',
  '.#............#.',
  '.#............#.',
  '.#.##..##..##.#.',
  '.#............#.',
  '.#............#.',
  '.#............#.',
  feet,
  B,
];
const GFRA = fright('.##..##..##..##.');
const GFRB = fright('..##..####..##..');

// ---- eyes going home ----
const GEYES = [
  B, B, B, B, B,
  '...##......##...',
  '..####....####..',
  '..####....####..',
  '...##......##...',
  B, B, B, B, B, B, B,
];

// ---- direction transforms (16x16) ----
const mirrorH = (img) => img.map((r) => [...pad(r)].reverse().join(''));
const rotCW = (img) => img.map((_, y) => [...Array(16)].map((_, x) => pad(img[15 - x])[y]).join(''));
const rotCCW = (img) => img.map((_, y) => [...Array(16)].map((_, x) => pad(img[x])[15 - y]).join(''));

// direction order everywhere in the game: 0 up, 1 left, 2 down, 3 right
const IMAGES = {
  PACC: PAC_CLOSED,
  PACH0: rotCCW(PAC_HALF_R), PACH1: mirrorH(PAC_HALF_R), PACH2: rotCW(PAC_HALF_R), PACH3: PAC_HALF_R,
  PACW0: rotCCW(PAC_WIDE_R), PACW1: mirrorH(PAC_WIDE_R), PACW2: rotCW(PAC_WIDE_R), PACW3: PAC_WIDE_R,
  GBODA, GBODB, GFRA, GFRB, GEYES,
};

const oct = (v) => v.toString(8);
let out = [];
for (const [name, img] of Object.entries(IMAGES)) {
  if (img.length !== 16) throw new Error(`${name}: ${img.length} rows`);
  out.push(`${name}:`);
  for (let phase = 0; phase < 8; phase += 2) {
    out.push(`\t; phase ${phase}`);
    for (const row of img) {
      const r = pad(row);
      if (r.length !== 16) throw new Error(`${name}: row '${row}'`);
      let w = 0;
      for (let i = 0; i < 16; i++) if (r[i] === '#') w |= 1 << i;
      w <<= phase;
      out.push(`\t.BYTE ${oct(w & 0xff)}, ${oct((w >> 8) & 0xff)}, ${oct((w >> 16) & 0xff)}`);
    }
  }
}

// run from the repo root: node tools/gen-sprites.mjs
const path = process.argv[2] ?? 'programs/pacman.s';
const src = readFileSync(path, 'utf8');
const BEGIN = '; --- sprites begin (generated by gen-sprites.mjs, do not edit) ---';
const END = '; --- sprites end ---';
const a = src.indexOf(BEGIN);
const b = src.indexOf(END);
if (a < 0 || b < 0) throw new Error('markers not found in ' + path);
writeFileSync(path, src.slice(0, a + BEGIN.length) + '\n' + out.join('\n') + '\n' + src.slice(b));
console.log(`spliced ${Object.keys(IMAGES).length} images, ${out.length} lines`);
